
-- Copy and paste this into your Supabase SQL Editor to set up the database

-- 1. Create the 'leads' table
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  company text,
  phone text
);

-- 2. Enable Security (Row Level Security)
-- This ensures that your data is safe and follows best practices.
alter table public.leads enable row level security;

-- 3. Create a Policy to allow the contact form to insert data
-- This allows any visitor (anonymous) to insert rows into the leads table,
-- but they cannot read, update, or delete existing data.
create policy "Enable insert for everyone" 
on public.leads 
for insert 
with check (true);

-- 4. Setup Complete
-- The form on the website will now successfully save data to this table.
